<?php

namespace FileParser\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-28 at 17:08:13.
 */
class BasicValidatorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var BasicValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BasicValidator();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->object = null;
    }

    /**
     * @covers FileParser\Service\BasicValidator::validateData
     */
    public function testValidateWithValidData() {
        
        $fullData = array(array("73-ou-XW46", "Apple", 1, array("a")));
        $result = $this->object->getValidData($fullData);
        $this->assertEquals($fullData, $result);
    }

    
    /**
     * @covers FileParser\Service\BasicValidator::validateData
     */
    public function testValidateWithInvalidId() {
        $fullData = array(array("80Gw-xT97","Pear","920",array("a")));
        $result = $this->object->getValidData($fullData);
        $this->assertEquals(array(), $result);
    }
    
}
