<?php

namespace FileParser\Service\Readers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-28 at 16:31:40.
 */
class CsvReaderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var CsvReader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CsvReader();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->object = null;
    }

    /**
     * @covers FileParser\Service\Readers\CsvReader::doesSourceExist
     */
    public function testDoesSourceExist() {
        //@todo need mockrey
        $result = $this->object->doesSourceExist("C:/Recovery.txt");
        $this->assertTrue($result);
    }

    /**
     * @covers FileParser\Service\Readers\CsvReader::readFromSource
     */
    public function testReadFromSource() {
        //@todo need mockrey
        $result = $this->object->readFromSource("D:\googledrive\documents\OTHER_TEAMS\NESS_INTERVIEW\php-candidate-test-master\items.csv");
        $this->assertNotEmpty($result);
    }

}
