<?php

namespace FileParser\Service\Readers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-28 at 17:41:19.
 */
class ReaderFactoryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @covers FileParser\Service\Readers\ReaderFactory::getReaderForFile
     */
    public function testGetReaderForFile() {
        $result = ReaderFactory::getReaderForFile("test.csv");
        $this->assertInstanceOf("FileParser\Service\Readers\CsvReader", $result);
    }

}
